[package]
name = "collider-py"
version = "0.1.0"
edition = "2024"

[lib]
name = "collider"
crate-type = ["cdylib"]
doc = false

[dependencies]
pyo3 = { workspace = true}
collider-rs = { workspace = true }
